
[package]
name = "dead-api"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "^1.18"
spl-token = { version = "^4", features = ["no-entrypoint"] }
coal-utils = "2.5.2"
borsh = "0.9.3"
